# An example of ClusterConfig showing different ways of setting nodegroup SSH keys:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ben-eks-cluster
  region: us-west-2

nodeGroups:
  - name: beard-nodegroup
    instanceType: m5.2xlarge
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: uswest2keypair
  