apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbatoolspowershellcontainer
spec:
  selector:
    matchLabels:
      app: dbatoolspowershellcontainer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: dbatoolspowershellcontainer
    spec:
      containers:
      - name: dbatoolspowershellcontainer
        image: sqldbawithabeard/pwshdbatools:v1
